name: main
on: push
jobs:
  test:
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: cedx/setup-hashlink@v1
      - run: hl --version
