name: main
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3
      - name: Set up Lix
        uses: lix-pm/setup-lix@master
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          lix download
          npm install
      - name: Run tests
        run: haxe test.hxml
      - name: Collect code coverage
        if: success()
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          path-to-lcov: var/lcov.info
  action:
    runs-on: ${{matrix.platform}}
    needs: test
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: cedx/setup-hashlink@v1
      - run: hl --version
